[project]
name = "helper-scripts"
version = "0.1.0"
description = "helper scripts for AlQuran app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "py5>=0.10.7a0",
    "requests>=2.32.5",
]
